------------------------------------------------------------------------------
 auto-generated
     This code was generated by a tool.
     Runtime Version4.0.30319.42000

     Changes to this file may cause incorrect behavior and will be lost if
     the code is regenerated.
 auto-generated
------------------------------------------------------------------------------

namespace lab_14.Properties
{


    [globalSystem.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [globalSystem.CodeDom.Compiler.GeneratedCodeAttribute(Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator, 11.0.0.0)]
    internal sealed partial class Settings  globalSystem.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(globalSystem.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
